[package]
name = "payload_filter"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
ngx = { git = "https://github.com/nginx/ngx-rust", version = "0.5.0", features = ["async", "serde", "vendored"] }
regex = "1"
anyhow = "1"